# Generated by Django 5.2.5 on 2025-08-23 12:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_return',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Add Delivery and return policy (HTML supported)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_chart',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Add size chart content here (HTML supported)', null=True),
        ),
    ]
