# Generated by Django 5.2.4 on 2025-07-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='button_url_name',
            field=models.URLField(help_text='Enter the URL Address', max_length=100, verbose_name='URL Address'),
        ),
    ]
