# Generated by Django 5.2.8 on 2025-11-23 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot question',
                'verbose_name_plural': 'Chatbot questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
