# Generated by Django 5.2.5 on 2025-10-18 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional: Show this ad only on specific category page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='shop.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional: When to stop showing this ad', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(help_text='Supports GIF and static images. Recommended size: 1200x500px', upload_to='ads/', verbose_name='Advertisement Image'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL to redirect when ad is clicked', max_length=500, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('home', 'Home Page'), ('category', 'Category Page'), ('product', 'Product Page'), ('all', 'All Pages')], default='home', help_text='Where this ad should be displayed', max_length=20, verbose_name='Placement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Optional: When to start showing this ad', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)'),
        ),
    ]
