# Generated by Django 5.2.7 on 2026-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_visitorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_photo',
            field=models.ImageField(blank=True, help_text='Upload transaction screenshot/proof for offline payments', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('offline_payment', 'Offline Payment (Instagram/Bank Transfer)')], max_length=50),
        ),
    ]
