# Generated by Django 5.2.5 on 2025-10-20 01:29

from django.db import migrations, models


def clear_contracts_for_id_change(apps, schema_editor):
    """
    Clear all contract data to allow ID field type change
    Note: This will delete all Contract, Payment, Review, and Message data
    """
    Contract = apps.get_model("freelancing", "Contract")

    # Print warning
    print("WARNING: This migration will delete all Contract-related data")
    print(f"Deleting {Contract.objects.count()} contracts and all related data...")

    # Delete all contracts (cascade will handle related objects)
    Contract.objects.all().delete()

    print("All contract data has been cleared.")


def reverse_migration(apps, schema_editor):
    """
    Reverse is not possible - data has been deleted
    """
    print("WARNING: Cannot reverse this migration - data was permanently deleted")


class Migration(migrations.Migration):

    dependencies = [
        ("freelancing", "0002_alter_contract_id"),
    ]

    operations = [
        # Step 1: Clear all contract data
        migrations.RunPython(clear_contracts_for_id_change, reverse_migration),
        # Step 2: Change the ID field type
        migrations.AlterField(
            model_name="contract",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
